apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-refresher-sa
  namespace: solar-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-refresher-role
  namespace: solar-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-refresher-binding
  namespace: solar-system
subjects:
- kind: ServiceAccount
  name: ecr-refresher-sa
roleRef:
  kind: Role
  name: ecr-refresher-role
  apiGroup: rbac.authorization.k8s.io