apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mongo-db-creds
  namespace: solar-system
spec:
  encryptedData:
    MONGO_URI: AgAztVpeVG8Ebsn9NNAvdvC7BoAw0Y4EV2GbvTc+pvR2ZCnBQAY28vXOE+w7bqNVFtReZdabOiSgK4fGSWrmht76L+L0pYKJH3K1wunHYdtEj6VfDZO00cqSpRGpESASBibhaGR3JDdfZCYtnyYs438m5biXKExx1S2imv0GGHVlsuO+RmA6tclMpKMcYltrD4OhqXwXZTMVDo8xZ9pQd9O5/rDNOmetM1KpCleaSgGmlf3jWUsrp7H8dsFzqha+i/RNxCQEqfAqRDRgiR1Jdx79qeGQE8bpz9OEOAcbVmBHDyM9gIyo3zPUaHl64HtBuVhpd9eZ9rB8qcGQ1cRZDq+ngH21+D25fy9WSb8hDKMgFy6b0452mWK0SgujWvcbQmTVVSaxn6DnHe448bxBF+q4n5mlDe9Q3krnFvDrV4zuFYzX2pO4yWHrmqU0vnjwhiY0cbAU0tlQaGEjQH0JGupr9VbxkCw1KRB8BFGWw2tnZLOMhjUE1CISSzcjrp7HxWKuRhOe9bxDW3DNZIG1cfvcddyCmpuUKqOLX3cP+dg62PxO++ECBJqRu4/ehPj7cqrvO+u+ACNJb+reDtSBcDr9qR/U/EC+/bIO1yWNFANGJxUr9jDIxcdg/BcthXP8oE91oCcbjjc4EbZ4XX2SAUon/QKcFxgX1DFbZ+JvvTd6eAEKPOvY6cQokxsQdVq/eA6i9HALTtp9bthu1gDwMjBa1PwalEsT3ewBBoDUY95CjNmOSL9Pgh1OeC+T6hrcock5LzQeV8N8E3o2ilWhQHv5v30bPjEEueIXlGJ7KH0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mongo-db-creds
      namespace: solar-system